"""Template for generating wrapper scripts."""

import os
import stat
from pathlib import Path
from typing import Optional

from ward.platform_utils import get_guarded_bin_dir, find_real_binary


# List of binaries to wrap
WRAPPED_BINARIES = [
    "find",
    "sh",
    "bash",
    "zsh",
    "python",
    "python3",
    "node",
    "tar",
]


# Python wrapper script template
PYTHON_WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
"""
ward wrapper for {binary}

This wrapper intercepts calls to {binary} and checks for dangerous patterns.
It logs all invocations and optionally blocks dangerous commands.

DO NOT MODIFY - Generated by ward
"""

import os
import sys

# Prevent import errors by adding the package to path
GUARD_DIR = os.path.expanduser("~/.ward")
sys.path.insert(0, os.path.join(GUARD_DIR, "lib"))

def main():
    # Check enforce mode
    enforce = os.environ.get("AICODE_GUARD_ENFORCE", "0") == "1"

    # Import guard module
    try:
        from ward.guard import guard_exec
        exit_code = guard_exec("{binary}", sys.argv, enforce=enforce)
        sys.exit(exit_code)
    except ImportError:
        # Fallback: just exec the real binary
        real_binary = find_real_binary_fallback("{binary}")
        if real_binary:
            os.execv(real_binary, sys.argv)
        else:
            print(f"[ward] ERROR: Could not find {binary}", file=sys.stderr)
            sys.exit(127)


def find_real_binary_fallback(binary):
    """Find real binary without importing ward."""
    guarded_bin = os.path.expanduser("~/.ward/guarded-bin")

    # System paths to search
    system_paths = [
        "/usr/bin",
        "/bin",
        "/usr/local/bin",
        "/opt/homebrew/bin",
    ]

    # Check PATH first, excluding guarded-bin
    path_dirs = os.environ.get("PATH", "").split(os.pathsep)
    for path_dir in path_dirs:
        if path_dir == guarded_bin:
            continue
        candidate = os.path.join(path_dir, binary)
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate

    # Fallback to system paths
    for path_dir in system_paths:
        candidate = os.path.join(path_dir, binary)
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate

    return None


if __name__ == "__main__":
    main()
'''


# Shell wrapper script template (simpler, fewer dependencies)
SHELL_WRAPPER_TEMPLATE = '''#!/bin/sh
# ward wrapper for {binary}
# DO NOT MODIFY - Generated by ward

BINARY="{binary}"
GUARD_DIR="$HOME/.ward"
LOG_FILE="$GUARD_DIR/logs/wrapper.log"
ENFORCE="${{AICODE_GUARD_ENFORCE:-0}}"

# Find real binary (skip guarded-bin directory)
find_real_binary() {{
    GUARDED_BIN="$GUARD_DIR/guarded-bin"

    # First check PATH, excluding guarded-bin
    IFS=':'
    for dir in $PATH; do
        if [ "$dir" != "$GUARDED_BIN" ] && [ -x "$dir/$BINARY" ]; then
            echo "$dir/$BINARY"
            return 0
        fi
    done
    unset IFS

    # Fallback to common system paths
    for dir in /usr/bin /bin /usr/local/bin /opt/homebrew/bin; do
        if [ -x "$dir/$BINARY" ]; then
            echo "$dir/$BINARY"
            return 0
        fi
    done

    return 1
}}

REAL_BINARY=$(find_real_binary)

if [ -z "$REAL_BINARY" ]; then
    echo "[ward] ERROR: Could not find $BINARY" >&2
    exit 127
fi

# Log the invocation
log_invocation() {{
    mkdir -p "$(dirname "$LOG_FILE")"
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "$TIMESTAMP|$BINARY|$*|$$|$PPID|$(pwd)" >> "$LOG_FILE"
}}

# Check for dangerous patterns
check_dangerous() {{
    case "$BINARY" in
        find)
            for arg in "$@"; do
                case "$arg" in
                    -exec|-execdir|-ok|-okdir)
                        return 0  # Dangerous
                        ;;
                esac
            done
            ;;
        sh|bash|zsh)
            for arg in "$@"; do
                case "$arg" in
                    -c)
                        return 0  # Dangerous
                        ;;
                esac
            done
            ;;
        python|python3)
            for arg in "$@"; do
                case "$arg" in
                    -c)
                        return 0  # Dangerous
                        ;;
                esac
            done
            ;;
        node)
            for arg in "$@"; do
                case "$arg" in
                    -e|--eval)
                        return 0  # Dangerous
                        ;;
                esac
            done
            ;;
        tar)
            for arg in "$@"; do
                case "$arg" in
                    --checkpoint-action=exec*)
                        return 0  # Dangerous
                        ;;
                esac
            done
            ;;
    esac
    return 1  # Safe
}}

# Log all invocations
log_invocation "$@"

# Check for dangerous patterns
if check_dangerous "$@"; then
    if [ "$ENFORCE" = "1" ]; then
        echo "[ward] BLOCKED: $BINARY with dangerous arguments" >&2
        echo "[ward] Args: $*" >&2
        echo "[ward] To allow, unset AICODE_GUARD_ENFORCE or modify policy" >&2
        exit 1
    else
        echo "[ward] WARNING: Detected dangerous pattern in $BINARY invocation" >&2
        echo "[ward] Args: $*" >&2
        echo "[ward] Running in observe-only mode (use --enforce to block)" >&2
    fi
fi

# Execute real binary
exec "$REAL_BINARY" "$@"
'''


def generate_wrapper(binary: str, use_python: bool = True) -> str:
    """Generate wrapper script content for a binary."""
    if use_python:
        return PYTHON_WRAPPER_TEMPLATE.format(binary=binary)
    else:
        return SHELL_WRAPPER_TEMPLATE.format(binary=binary)


def install_wrapper(binary: str, use_python: bool = False) -> Optional[Path]:
    """
    Install a wrapper script for a binary.

    Args:
        binary: Name of the binary to wrap
        use_python: Use Python wrapper (more features) vs shell wrapper (simpler)

    Returns:
        Path to installed wrapper, or None on failure
    """
    guarded_bin = get_guarded_bin_dir()
    guarded_bin.mkdir(parents=True, exist_ok=True)

    wrapper_path = guarded_bin / binary
    content = generate_wrapper(binary, use_python)

    try:
        # Write wrapper script
        with open(wrapper_path, "w") as f:
            f.write(content)

        # Make executable
        wrapper_path.chmod(wrapper_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        return wrapper_path
    except Exception as e:
        print(f"Failed to install wrapper for {binary}: {e}")
        return None


def install_all_wrappers(use_python: bool = False) -> list[str]:
    """
    Install wrapper scripts for all risky binaries.

    Returns:
        List of successfully installed wrapper names
    """
    installed = []

    for binary in WRAPPED_BINARIES:
        # Check if the real binary exists
        real_path = find_real_binary(binary)
        if real_path is None:
            continue

        result = install_wrapper(binary, use_python)
        if result:
            installed.append(binary)

    return installed


def remove_wrapper(binary: str) -> bool:
    """Remove a wrapper script."""
    guarded_bin = get_guarded_bin_dir()
    wrapper_path = guarded_bin / binary

    try:
        if wrapper_path.exists():
            wrapper_path.unlink()
        return True
    except Exception:
        return False


def remove_all_wrappers() -> list[str]:
    """
    Remove all wrapper scripts.

    Returns:
        List of removed wrapper names
    """
    removed = []
    guarded_bin = get_guarded_bin_dir()

    if not guarded_bin.exists():
        return removed

    for wrapper in guarded_bin.iterdir():
        if wrapper.is_file():
            try:
                wrapper.unlink()
                removed.append(wrapper.name)
            except Exception:
                pass

    return removed


def get_installed_wrappers() -> list[str]:
    """Get list of installed wrapper names."""
    guarded_bin = get_guarded_bin_dir()

    if not guarded_bin.exists():
        return []

    return [f.name for f in guarded_bin.iterdir() if f.is_file()]
